### ISSUE TITLE
slow gps connection

### ISSUE THREAD

**Issue by alexbraschel** [fhorinek/BB#104]
when starting the strato it takes up to 3 minutes to get a gps connection. before update 166 it was just like immedeatly connected

**Comment by fhorinek** [comment]
Strato firmware does not affect the gnss fix speed, it is separate system.
The longer fixed might be expected after power loss or after you change your location with strato power off.

**Comment by fhorinek** [comment]
I think that your device might be in the init state for too long. I am trying to replicate this problem on my development device to fix it.

Can you try to go inside GNSS settings, maybe you will see Device Init under the Status

I think that i might be linked to https://github.com/fhorinek/BB/issues/113 and https://github.com/fhorinek/BB/issues/96

**Comment by thrull** [comment]
I might be wrong but ublox documentation says that hardware "reset" clears the locations data cache and since we are performing reset in ublox_init() we are always clearing the "cache" - so no warm/hot start is not possible. 

`	GpioWrite(GNSS_RST, LOW);
	osDelay(100);
	GpioWrite(GNSS_RST, HIGH);`

Should we call "UBX-CFG-RST" command instead (with warm/hot startup flags) instead of hardware reset? I will explore this during next few days and submit patch.
