### ISSUE TITLE
unable to update

### ISSUE THREAD

**Issue by KrzysiekJ13** [fhorinek/BB#19]
ver D0000114
update found, but an error occurres - connection timeout .

**Comment by fhorinek** [comment]
Please try manually update to 
https://strato.skybean.eu/fw/133/

then make sure that server url in config/device.cfg is
server_url=https://strato.skybean.eu/update

o remove the config file to reset to default settings

**Comment by KrzysiekJ13** [comment]
Hi,
i've downloaded fw133 and copied it to the folder strato-system-fw and
nothing happened.
How am I supposed to update it manually?

the server url was correct, i have also deleted the config file.




Pozdrawiam
Krzysztof Jagło


wt., 20 lip 2021 o 12:58 František Horínek ***@***.***>
napisał(a):

**Comment by fhorinek** [comment]
copy the strato.fw to the main directory (lowest level, root)

**Comment by KrzysiekJ13** [comment]
success, FW updated!
thx

Pozdrawiam
Krzysztof Jagło


śr., 21 lip 2021 o 10:19 František Horínek ***@***.***>
napisał(a):

**Comment by BoehniM** [comment]
V133: Trying to change QNH causes crash

**Comment by theosch1** [comment]
There are two widgets which I am really still missing. Airspace visualization on the map (even more important than warnings) and IGC-upload cable-free. The vario audio still is not intuitively understandable, I tested both files given so far and I dont't want to start programming it myself. May be it is possible to transfer/adopt the audio from Competino, C-Pilot pro etc.

**Comment by simonseyer** [comment]
> There are two widgets which I am really still missing. Airspace visualization on the map (even more important than warnings) and IGC-upload cable-free. The vario audio still is not intuitively understandable, I tested both files given so far and I dont't want to start programming it myself. May be it is possible to transfer/adopt the audio from Competino, C-Pilot pro etc. 

@theosch1 thanks for the report. It would be great if you could create separate tickets for your feature requests. That would help with discussing them.

Regarding the upload of igc files: what would be the most convenient upload location for you? So where should the files be sent?

**Comment by theosch1** [comment]
o.k., Airspace visualization on the map is very important in West Germany, since 90% of the flying sites are inside airspace, or better say below them. Therefore in the C-pilot I used to put the lower levels of the airspace inside those areas. Then you can see during the flight, what the maximum height allowed is in the next airspaces ahead of you. Since I am a friend of simplicity, a 2 digit number would be sufficient like in flight levels, because typically the lower borders are 2500, 3500, 4500, 5500 feet, followed by flight level 65. Accordingly 25 would read 2500 feet (760 m). I also like the system of xc-track, giving the vertical and horizontal distance to the next airspace. Often there are several airspaces above each other, but only the lowest border is relevant for us. Therefore all others should be dropped (during flight simplicity helps a lot). Control zones and restricted areas should be of different colour, because they start on the ground and end at an upper level (most often around 1000 m). In these cases only the upper border is interesting.

**Comment by theosch1** [comment]
For  the beginning, it would be sufficient to upload igc-files to the smartphone, i.e. by Bluetooth. Then you can proceed to upload it to the servers of interest. Most users upload to more than one server, Therefore, for a direct upload several pre-chosen addresses should be available to insert. I personally use the DHV-XC, the XCCup and the XC-Contest (which is directly available in XC-Track)

**Comment by theosch1** [comment]
Nowadays championships often demand online tracking by flymaster. May be this could be realized by tethering with your smartphone. Normally organizers offer renting of a tracker, but a private solution would be fine of course.

**Comment by theosch1** [comment]
Flarm did not work with the actual FW. After updating my Competino+ Flarm FW, I tested it with the TTGO LoRa and the Strato. The Competino+ is detected by the TTGO LoRa and vice versa, but the Strato cannot be seen by neither of them. By the way, is the FANET ID identical with the Flarm ID? Only the first one is given in the settings.
