### ISSUE TITLE
Fix 00010000: LVGL error ../App/lib/lvgl/src/lv_core/lv_style.c:778 (_lv_style_list_set_local_color) _lv_style_list_set_local_color (USAGE_FAULT, UNDEFINSTR) in _lv_log_add (lv_log.c:90)

### ISSUE THREAD

**Issue by fhorinek** [fhorinek/BB#348]
### Reason ###

00010000: LVGL error ../App/lib/lvgl/src/lv_core/lv_style.c:778 (_lv_style_list_set_local_color) _lv_style_list_set_local_color (USAGE_FAULT, UNDEFINSTR)

### Link to App Center ###

* [https://appcenter.ms/users/fhorinek/apps/Strato/crashes/errors/657997599u](https://appcenter.ms/users/fhorinek/apps/Strato/crashes/errors/657997599u)

**Comment by bubeck** [comment]
First analysis:

The update on VarioBar fails in line
https://github.com/fhorinek/BB/blob/6301d6521cd072df3118d140e585ae4dcc6c3fdc/BB3/App/gui/widgets/types/widget_vario_bar.c#L151

in lv_obj it tries to get the style of the MAIN_PART with
https://github.com/fhorinek/BB/blob/6301d6521cd072df3118d140e585ae4dcc6c3fdc/BB3/App/lib/lvgl/src/lv_core/lv_obj.c#L1310

and by using this style it fails in 
https://github.com/fhorinek/BB/blob/6301d6521cd072df3118d140e585ae4dcc6c3fdc/BB3/App/lib/lvgl/src/lv_core/lv_style.c#L778

So this style seems to be invalid.

I dont see, how it gets invalid and what the reason is.
