### ISSUE TITLE
Vario freeze on high volume

### ISSUE THREAD

**Issue by fhorinek** [fhorinek/BB#5]
When I set audio sound to 95% and enable vario sound, device has frozen and cannot be started, cannot be reseted. Only when I connect power adapter for a second then I am able to start vario again. Too big power consumption?

**Comment by fhorinek** [comment]
It is caused by the battery protection circuit.
The volume control is directly fed to amplifier register.
We need to limit the maximum volume anyway to protect the speaker

**Comment by tomasz13** [comment]
the issue is closed, because in the FWBuild 138 may be a fix for this, but I found the same issue in  FW-D0000166 

I have set 100% volume in the Bluetooth menu & after some peeps the device has frozen and cannot be started, cannot be reseted. Only when I connect power adapter for a second then I am able to start vario again.
please check it and fix it again ;)
